name: Hello Github Actions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  NODE_VERSION: "18"

jobs:
  hello-job:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout do código
            uses: actions/checkout@v4

        - name: Exibir mensagem de boas-vindas
          run: echo "Olá, GitHub Actions!"
  demonstrando-estrutura:
    name: Demonstrando Estrutura Básica
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Executar Hello World
        run: echo "Hello Github Actions!"

      - name: 
        run: |
          echo "Sistema Operqacional: ${{ runner.os}}"
          echo "Diretório atual: ${ pwd }"
          echo "Data atual: ${ date }"
          echo "Sistema Operqacional: ${ whoami }"

      - name: Listar arquivos do repositório
        run: ls -la

      - name: Comandos múltiplos
        run: |
          echo "Este é o Lab 01 do curso de GitHub Actions"
          echo "Workflow executado com sucesso!"
          echo "Pronto para o próximo desafio!"